// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Carnet               string   `protobuf:"bytes,2,opt,name=carnet,proto3" json:"carnet,omitempty"`
	Nombre               string   `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Curso                string   `protobuf:"bytes,4,opt,name=curso,proto3" json:"curso,omitempty"`
	Nota                 string   `protobuf:"bytes,5,opt,name=nota,proto3" json:"nota,omitempty"`
	Semestre             string   `protobuf:"bytes,6,opt,name=semestre,proto3" json:"semestre,omitempty"`
	Year                 string   `protobuf:"bytes,7,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCarnet() string {
	if m != nil {
		return m.Carnet
	}
	return ""
}

func (m *User) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *User) GetCurso() string {
	if m != nil {
		return m.Curso
	}
	return ""
}

func (m *User) GetNota() string {
	if m != nil {
		return m.Nota
	}
	return ""
}

func (m *User) GetSemestre() string {
	if m != nil {
		return m.Semestre
	}
	return ""
}

func (m *User) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

type UserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbf, 0x8a, 0xc2, 0x40,
	0x10, 0xc6, 0x49, 0x2e, 0x7f, 0xee, 0xe6, 0x8e, 0x2b, 0x86, 0xe3, 0x58, 0x02, 0x8a, 0xa4, 0xb2,
	0x4a, 0xa1, 0x8f, 0x60, 0x21, 0xb6, 0x11, 0x1f, 0x60, 0x93, 0x4c, 0x91, 0x22, 0x59, 0x9d, 0xdd,
	0x08, 0xbe, 0x8d, 0x8f, 0x2a, 0x3b, 0x1b, 0x44, 0xec, 0xe6, 0xf7, 0x9b, 0x6f, 0xe1, 0xdb, 0x01,
	0x98, 0x2c, 0x71, 0x75, 0x66, 0xe3, 0x4c, 0x79, 0x8f, 0x20, 0x39, 0x59, 0x62, 0xfc, 0x85, 0xb8,
	0xef, 0x54, 0xb4, 0x8a, 0xd6, 0x5f, 0x75, 0xdc, 0x77, 0xf8, 0x0f, 0x59, 0xab, 0x79, 0x24, 0xa7,
	0x62, 0x71, 0x33, 0x79, 0x3f, 0x9a, 0xa1, 0x61, 0x52, 0x1f, 0xc1, 0x07, 0xc2, 0x3f, 0x48, 0xdb,
	0x89, 0xad, 0x51, 0x89, 0xe8, 0x00, 0x88, 0x90, 0x8c, 0xc6, 0x69, 0x95, 0x8a, 0x94, 0x19, 0x0b,
	0xf8, 0xb4, 0x34, 0x90, 0x75, 0x4c, 0x2a, 0x13, 0xff, 0x64, 0x9f, 0xbf, 0x91, 0x66, 0x95, 0x87,
	0xbc, 0x9f, 0xcb, 0x05, 0x7c, 0xfb, 0x86, 0x35, 0x5d, 0x26, 0xb2, 0xee, 0xbd, 0xe8, 0xe6, 0x10,
	0xd6, 0x47, 0xe2, 0x6b, 0xdf, 0x12, 0x2e, 0x21, 0xdf, 0x93, 0x93, 0x2f, 0xfd, 0x54, 0x2f, 0xef,
	0x8a, 0x54, 0x08, 0x0b, 0x80, 0x1d, 0x93, 0x76, 0x24, 0x14, 0xe4, 0xbc, 0x6b, 0x32, 0xb9, 0xc9,
	0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0x15, 0x8f, 0xb2, 0x13, 0x21, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *UserRequest) (*User, error)
	CreateUser(context.Context, *User) (*User, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
